// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"gopkg.in/telebot.v4"
)

// NewMockContext creates a new instance of MockContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContext {
	mock := &MockContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContext is an autogenerated mock type for the Context type
type MockContext struct {
	mock.Mock
}

type MockContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContext) EXPECT() *MockContext_Expecter {
	return &MockContext_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockContext
func (_mock *MockContext) Accept(errorMessage ...string) error {
	var tmpRet mock.Arguments
	if len(errorMessage) > 0 {
		tmpRet = _mock.Called(errorMessage)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...string) error); ok {
		r0 = returnFunc(errorMessage...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockContext_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - errorMessage ...string
func (_e *MockContext_Expecter) Accept(errorMessage ...interface{}) *MockContext_Accept_Call {
	return &MockContext_Accept_Call{Call: _e.mock.On("Accept",
		append([]interface{}{}, errorMessage...)...)}
}

func (_c *MockContext_Accept_Call) Run(run func(errorMessage ...string)) *MockContext_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockContext_Accept_Call) Return(err error) *MockContext_Accept_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Accept_Call) RunAndReturn(run func(errorMessage ...string) error) *MockContext_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Answer provides a mock function for the type MockContext
func (_mock *MockContext) Answer(resp *telebot.QueryResponse) error {
	ret := _mock.Called(resp)

	if len(ret) == 0 {
		panic("no return value specified for Answer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*telebot.QueryResponse) error); ok {
		r0 = returnFunc(resp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Answer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Answer'
type MockContext_Answer_Call struct {
	*mock.Call
}

// Answer is a helper method to define mock.On call
//   - resp *telebot.QueryResponse
func (_e *MockContext_Expecter) Answer(resp interface{}) *MockContext_Answer_Call {
	return &MockContext_Answer_Call{Call: _e.mock.On("Answer", resp)}
}

func (_c *MockContext_Answer_Call) Run(run func(resp *telebot.QueryResponse)) *MockContext_Answer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *telebot.QueryResponse
		if args[0] != nil {
			arg0 = args[0].(*telebot.QueryResponse)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Answer_Call) Return(err error) *MockContext_Answer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Answer_Call) RunAndReturn(run func(resp *telebot.QueryResponse) error) *MockContext_Answer_Call {
	_c.Call.Return(run)
	return _c
}

// Args provides a mock function for the type MockContext
func (_mock *MockContext) Args() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Args")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockContext_Args_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Args'
type MockContext_Args_Call struct {
	*mock.Call
}

// Args is a helper method to define mock.On call
func (_e *MockContext_Expecter) Args() *MockContext_Args_Call {
	return &MockContext_Args_Call{Call: _e.mock.On("Args")}
}

func (_c *MockContext_Args_Call) Run(run func()) *MockContext_Args_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Args_Call) Return(strings []string) *MockContext_Args_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockContext_Args_Call) RunAndReturn(run func() []string) *MockContext_Args_Call {
	_c.Call.Return(run)
	return _c
}

// Boost provides a mock function for the type MockContext
func (_mock *MockContext) Boost() *telebot.BoostUpdated {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Boost")
	}

	var r0 *telebot.BoostUpdated
	if returnFunc, ok := ret.Get(0).(func() *telebot.BoostUpdated); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.BoostUpdated)
		}
	}
	return r0
}

// MockContext_Boost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Boost'
type MockContext_Boost_Call struct {
	*mock.Call
}

// Boost is a helper method to define mock.On call
func (_e *MockContext_Expecter) Boost() *MockContext_Boost_Call {
	return &MockContext_Boost_Call{Call: _e.mock.On("Boost")}
}

func (_c *MockContext_Boost_Call) Run(run func()) *MockContext_Boost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Boost_Call) Return(boostUpdated *telebot.BoostUpdated) *MockContext_Boost_Call {
	_c.Call.Return(boostUpdated)
	return _c
}

func (_c *MockContext_Boost_Call) RunAndReturn(run func() *telebot.BoostUpdated) *MockContext_Boost_Call {
	_c.Call.Return(run)
	return _c
}

// BoostRemoved provides a mock function for the type MockContext
func (_mock *MockContext) BoostRemoved() *telebot.BoostRemoved {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BoostRemoved")
	}

	var r0 *telebot.BoostRemoved
	if returnFunc, ok := ret.Get(0).(func() *telebot.BoostRemoved); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.BoostRemoved)
		}
	}
	return r0
}

// MockContext_BoostRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BoostRemoved'
type MockContext_BoostRemoved_Call struct {
	*mock.Call
}

// BoostRemoved is a helper method to define mock.On call
func (_e *MockContext_Expecter) BoostRemoved() *MockContext_BoostRemoved_Call {
	return &MockContext_BoostRemoved_Call{Call: _e.mock.On("BoostRemoved")}
}

func (_c *MockContext_BoostRemoved_Call) Run(run func()) *MockContext_BoostRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_BoostRemoved_Call) Return(boostRemoved *telebot.BoostRemoved) *MockContext_BoostRemoved_Call {
	_c.Call.Return(boostRemoved)
	return _c
}

func (_c *MockContext_BoostRemoved_Call) RunAndReturn(run func() *telebot.BoostRemoved) *MockContext_BoostRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// Bot provides a mock function for the type MockContext
func (_mock *MockContext) Bot() telebot.API {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bot")
	}

	var r0 telebot.API
	if returnFunc, ok := ret.Get(0).(func() telebot.API); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telebot.API)
		}
	}
	return r0
}

// MockContext_Bot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bot'
type MockContext_Bot_Call struct {
	*mock.Call
}

// Bot is a helper method to define mock.On call
func (_e *MockContext_Expecter) Bot() *MockContext_Bot_Call {
	return &MockContext_Bot_Call{Call: _e.mock.On("Bot")}
}

func (_c *MockContext_Bot_Call) Run(run func()) *MockContext_Bot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Bot_Call) Return(aPI telebot.API) *MockContext_Bot_Call {
	_c.Call.Return(aPI)
	return _c
}

func (_c *MockContext_Bot_Call) RunAndReturn(run func() telebot.API) *MockContext_Bot_Call {
	_c.Call.Return(run)
	return _c
}

// Callback provides a mock function for the type MockContext
func (_mock *MockContext) Callback() *telebot.Callback {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Callback")
	}

	var r0 *telebot.Callback
	if returnFunc, ok := ret.Get(0).(func() *telebot.Callback); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Callback)
		}
	}
	return r0
}

// MockContext_Callback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Callback'
type MockContext_Callback_Call struct {
	*mock.Call
}

// Callback is a helper method to define mock.On call
func (_e *MockContext_Expecter) Callback() *MockContext_Callback_Call {
	return &MockContext_Callback_Call{Call: _e.mock.On("Callback")}
}

func (_c *MockContext_Callback_Call) Run(run func()) *MockContext_Callback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Callback_Call) Return(callback *telebot.Callback) *MockContext_Callback_Call {
	_c.Call.Return(callback)
	return _c
}

func (_c *MockContext_Callback_Call) RunAndReturn(run func() *telebot.Callback) *MockContext_Callback_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function for the type MockContext
func (_mock *MockContext) Chat() *telebot.Chat {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *telebot.Chat
	if returnFunc, ok := ret.Get(0).(func() *telebot.Chat); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Chat)
		}
	}
	return r0
}

// MockContext_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockContext_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
func (_e *MockContext_Expecter) Chat() *MockContext_Chat_Call {
	return &MockContext_Chat_Call{Call: _e.mock.On("Chat")}
}

func (_c *MockContext_Chat_Call) Run(run func()) *MockContext_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Chat_Call) Return(chat *telebot.Chat) *MockContext_Chat_Call {
	_c.Call.Return(chat)
	return _c
}

func (_c *MockContext_Chat_Call) RunAndReturn(run func() *telebot.Chat) *MockContext_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// ChatJoinRequest provides a mock function for the type MockContext
func (_mock *MockContext) ChatJoinRequest() *telebot.ChatJoinRequest {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatJoinRequest")
	}

	var r0 *telebot.ChatJoinRequest
	if returnFunc, ok := ret.Get(0).(func() *telebot.ChatJoinRequest); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.ChatJoinRequest)
		}
	}
	return r0
}

// MockContext_ChatJoinRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatJoinRequest'
type MockContext_ChatJoinRequest_Call struct {
	*mock.Call
}

// ChatJoinRequest is a helper method to define mock.On call
func (_e *MockContext_Expecter) ChatJoinRequest() *MockContext_ChatJoinRequest_Call {
	return &MockContext_ChatJoinRequest_Call{Call: _e.mock.On("ChatJoinRequest")}
}

func (_c *MockContext_ChatJoinRequest_Call) Run(run func()) *MockContext_ChatJoinRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_ChatJoinRequest_Call) Return(chatJoinRequest *telebot.ChatJoinRequest) *MockContext_ChatJoinRequest_Call {
	_c.Call.Return(chatJoinRequest)
	return _c
}

func (_c *MockContext_ChatJoinRequest_Call) RunAndReturn(run func() *telebot.ChatJoinRequest) *MockContext_ChatJoinRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ChatMember provides a mock function for the type MockContext
func (_mock *MockContext) ChatMember() *telebot.ChatMemberUpdate {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatMember")
	}

	var r0 *telebot.ChatMemberUpdate
	if returnFunc, ok := ret.Get(0).(func() *telebot.ChatMemberUpdate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.ChatMemberUpdate)
		}
	}
	return r0
}

// MockContext_ChatMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatMember'
type MockContext_ChatMember_Call struct {
	*mock.Call
}

// ChatMember is a helper method to define mock.On call
func (_e *MockContext_Expecter) ChatMember() *MockContext_ChatMember_Call {
	return &MockContext_ChatMember_Call{Call: _e.mock.On("ChatMember")}
}

func (_c *MockContext_ChatMember_Call) Run(run func()) *MockContext_ChatMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_ChatMember_Call) Return(chatMemberUpdate *telebot.ChatMemberUpdate) *MockContext_ChatMember_Call {
	_c.Call.Return(chatMemberUpdate)
	return _c
}

func (_c *MockContext_ChatMember_Call) RunAndReturn(run func() *telebot.ChatMemberUpdate) *MockContext_ChatMember_Call {
	_c.Call.Return(run)
	return _c
}

// Data provides a mock function for the type MockContext
func (_mock *MockContext) Data() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContext_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MockContext_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
func (_e *MockContext_Expecter) Data() *MockContext_Data_Call {
	return &MockContext_Data_Call{Call: _e.mock.On("Data")}
}

func (_c *MockContext_Data_Call) Run(run func()) *MockContext_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Data_Call) Return(s string) *MockContext_Data_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContext_Data_Call) RunAndReturn(run func() string) *MockContext_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockContext
func (_mock *MockContext) Delete() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockContext_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
func (_e *MockContext_Expecter) Delete() *MockContext_Delete_Call {
	return &MockContext_Delete_Call{Call: _e.mock.On("Delete")}
}

func (_c *MockContext_Delete_Call) Run(run func()) *MockContext_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Delete_Call) Return(err error) *MockContext_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Delete_Call) RunAndReturn(run func() error) *MockContext_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAfter provides a mock function for the type MockContext
func (_mock *MockContext) DeleteAfter(d time.Duration) *time.Timer {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAfter")
	}

	var r0 *time.Timer
	if returnFunc, ok := ret.Get(0).(func(time.Duration) *time.Timer); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Timer)
		}
	}
	return r0
}

// MockContext_DeleteAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAfter'
type MockContext_DeleteAfter_Call struct {
	*mock.Call
}

// DeleteAfter is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockContext_Expecter) DeleteAfter(d interface{}) *MockContext_DeleteAfter_Call {
	return &MockContext_DeleteAfter_Call{Call: _e.mock.On("DeleteAfter", d)}
}

func (_c *MockContext_DeleteAfter_Call) Run(run func(d time.Duration)) *MockContext_DeleteAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_DeleteAfter_Call) Return(timer *time.Timer) *MockContext_DeleteAfter_Call {
	_c.Call.Return(timer)
	return _c
}

func (_c *MockContext_DeleteAfter_Call) RunAndReturn(run func(d time.Duration) *time.Timer) *MockContext_DeleteAfter_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function for the type MockContext
func (_mock *MockContext) Edit(what interface{}, opts ...interface{}) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(what, opts)
	} else {
		tmpRet = _mock.Called(what)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = returnFunc(what, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Edit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edit'
type MockContext_Edit_Call struct {
	*mock.Call
}

// Edit is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) Edit(what interface{}, opts ...interface{}) *MockContext_Edit_Call {
	return &MockContext_Edit_Call{Call: _e.mock.On("Edit",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_Edit_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_Edit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContext_Edit_Call) Return(err error) *MockContext_Edit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Edit_Call) RunAndReturn(run func(what interface{}, opts ...interface{}) error) *MockContext_Edit_Call {
	_c.Call.Return(run)
	return _c
}

// EditCaption provides a mock function for the type MockContext
func (_mock *MockContext) EditCaption(caption string, opts ...interface{}) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(caption, opts)
	} else {
		tmpRet = _mock.Called(caption)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EditCaption")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) error); ok {
		r0 = returnFunc(caption, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_EditCaption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditCaption'
type MockContext_EditCaption_Call struct {
	*mock.Call
}

// EditCaption is a helper method to define mock.On call
//   - caption string
//   - opts ...interface{}
func (_e *MockContext_Expecter) EditCaption(caption interface{}, opts ...interface{}) *MockContext_EditCaption_Call {
	return &MockContext_EditCaption_Call{Call: _e.mock.On("EditCaption",
		append([]interface{}{caption}, opts...)...)}
}

func (_c *MockContext_EditCaption_Call) Run(run func(caption string, opts ...interface{})) *MockContext_EditCaption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContext_EditCaption_Call) Return(err error) *MockContext_EditCaption_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_EditCaption_Call) RunAndReturn(run func(caption string, opts ...interface{}) error) *MockContext_EditCaption_Call {
	_c.Call.Return(run)
	return _c
}

// EditOrReply provides a mock function for the type MockContext
func (_mock *MockContext) EditOrReply(what interface{}, opts ...interface{}) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(what, opts)
	} else {
		tmpRet = _mock.Called(what)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EditOrReply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = returnFunc(what, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_EditOrReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditOrReply'
type MockContext_EditOrReply_Call struct {
	*mock.Call
}

// EditOrReply is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) EditOrReply(what interface{}, opts ...interface{}) *MockContext_EditOrReply_Call {
	return &MockContext_EditOrReply_Call{Call: _e.mock.On("EditOrReply",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_EditOrReply_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_EditOrReply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContext_EditOrReply_Call) Return(err error) *MockContext_EditOrReply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_EditOrReply_Call) RunAndReturn(run func(what interface{}, opts ...interface{}) error) *MockContext_EditOrReply_Call {
	_c.Call.Return(run)
	return _c
}

// EditOrSend provides a mock function for the type MockContext
func (_mock *MockContext) EditOrSend(what interface{}, opts ...interface{}) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(what, opts)
	} else {
		tmpRet = _mock.Called(what)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EditOrSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = returnFunc(what, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_EditOrSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditOrSend'
type MockContext_EditOrSend_Call struct {
	*mock.Call
}

// EditOrSend is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) EditOrSend(what interface{}, opts ...interface{}) *MockContext_EditOrSend_Call {
	return &MockContext_EditOrSend_Call{Call: _e.mock.On("EditOrSend",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_EditOrSend_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_EditOrSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContext_EditOrSend_Call) Return(err error) *MockContext_EditOrSend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_EditOrSend_Call) RunAndReturn(run func(what interface{}, opts ...interface{}) error) *MockContext_EditOrSend_Call {
	_c.Call.Return(run)
	return _c
}

// Entities provides a mock function for the type MockContext
func (_mock *MockContext) Entities() telebot.Entities {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Entities")
	}

	var r0 telebot.Entities
	if returnFunc, ok := ret.Get(0).(func() telebot.Entities); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telebot.Entities)
		}
	}
	return r0
}

// MockContext_Entities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entities'
type MockContext_Entities_Call struct {
	*mock.Call
}

// Entities is a helper method to define mock.On call
func (_e *MockContext_Expecter) Entities() *MockContext_Entities_Call {
	return &MockContext_Entities_Call{Call: _e.mock.On("Entities")}
}

func (_c *MockContext_Entities_Call) Run(run func()) *MockContext_Entities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Entities_Call) Return(entities telebot.Entities) *MockContext_Entities_Call {
	_c.Call.Return(entities)
	return _c
}

func (_c *MockContext_Entities_Call) RunAndReturn(run func() telebot.Entities) *MockContext_Entities_Call {
	_c.Call.Return(run)
	return _c
}

// Forward provides a mock function for the type MockContext
func (_mock *MockContext) Forward(msg telebot.Editable, opts ...interface{}) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(msg, opts)
	} else {
		tmpRet = _mock.Called(msg)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Forward")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(telebot.Editable, ...interface{}) error); ok {
		r0 = returnFunc(msg, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type MockContext_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - msg telebot.Editable
//   - opts ...interface{}
func (_e *MockContext_Expecter) Forward(msg interface{}, opts ...interface{}) *MockContext_Forward_Call {
	return &MockContext_Forward_Call{Call: _e.mock.On("Forward",
		append([]interface{}{msg}, opts...)...)}
}

func (_c *MockContext_Forward_Call) Run(run func(msg telebot.Editable, opts ...interface{})) *MockContext_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telebot.Editable
		if args[0] != nil {
			arg0 = args[0].(telebot.Editable)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContext_Forward_Call) Return(err error) *MockContext_Forward_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Forward_Call) RunAndReturn(run func(msg telebot.Editable, opts ...interface{}) error) *MockContext_Forward_Call {
	_c.Call.Return(run)
	return _c
}

// ForwardTo provides a mock function for the type MockContext
func (_mock *MockContext) ForwardTo(to telebot.Recipient, opts ...interface{}) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(to, opts)
	} else {
		tmpRet = _mock.Called(to)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ForwardTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(telebot.Recipient, ...interface{}) error); ok {
		r0 = returnFunc(to, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_ForwardTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForwardTo'
type MockContext_ForwardTo_Call struct {
	*mock.Call
}

// ForwardTo is a helper method to define mock.On call
//   - to telebot.Recipient
//   - opts ...interface{}
func (_e *MockContext_Expecter) ForwardTo(to interface{}, opts ...interface{}) *MockContext_ForwardTo_Call {
	return &MockContext_ForwardTo_Call{Call: _e.mock.On("ForwardTo",
		append([]interface{}{to}, opts...)...)}
}

func (_c *MockContext_ForwardTo_Call) Run(run func(to telebot.Recipient, opts ...interface{})) *MockContext_ForwardTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telebot.Recipient
		if args[0] != nil {
			arg0 = args[0].(telebot.Recipient)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContext_ForwardTo_Call) Return(err error) *MockContext_ForwardTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_ForwardTo_Call) RunAndReturn(run func(to telebot.Recipient, opts ...interface{}) error) *MockContext_ForwardTo_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockContext
func (_mock *MockContext) Get(key string) interface{} {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// MockContext_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContext_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockContext_Expecter) Get(key interface{}) *MockContext_Get_Call {
	return &MockContext_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockContext_Get_Call) Run(run func(key string)) *MockContext_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Get_Call) Return(ifaceVal interface{}) *MockContext_Get_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *MockContext_Get_Call) RunAndReturn(run func(key string) interface{}) *MockContext_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InlineResult provides a mock function for the type MockContext
func (_mock *MockContext) InlineResult() *telebot.InlineResult {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InlineResult")
	}

	var r0 *telebot.InlineResult
	if returnFunc, ok := ret.Get(0).(func() *telebot.InlineResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.InlineResult)
		}
	}
	return r0
}

// MockContext_InlineResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InlineResult'
type MockContext_InlineResult_Call struct {
	*mock.Call
}

// InlineResult is a helper method to define mock.On call
func (_e *MockContext_Expecter) InlineResult() *MockContext_InlineResult_Call {
	return &MockContext_InlineResult_Call{Call: _e.mock.On("InlineResult")}
}

func (_c *MockContext_InlineResult_Call) Run(run func()) *MockContext_InlineResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_InlineResult_Call) Return(inlineResult *telebot.InlineResult) *MockContext_InlineResult_Call {
	_c.Call.Return(inlineResult)
	return _c
}

func (_c *MockContext_InlineResult_Call) RunAndReturn(run func() *telebot.InlineResult) *MockContext_InlineResult_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function for the type MockContext
func (_mock *MockContext) Message() *telebot.Message {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 *telebot.Message
	if returnFunc, ok := ret.Get(0).(func() *telebot.Message); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Message)
		}
	}
	return r0
}

// MockContext_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type MockContext_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *MockContext_Expecter) Message() *MockContext_Message_Call {
	return &MockContext_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *MockContext_Message_Call) Run(run func()) *MockContext_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Message_Call) Return(message *telebot.Message) *MockContext_Message_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockContext_Message_Call) RunAndReturn(run func() *telebot.Message) *MockContext_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Migration provides a mock function for the type MockContext
func (_mock *MockContext) Migration() (int64, int64) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Migration")
	}

	var r0 int64
	var r1 int64
	if returnFunc, ok := ret.Get(0).(func() (int64, int64)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() int64); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(int64)
	}
	return r0, r1
}

// MockContext_Migration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migration'
type MockContext_Migration_Call struct {
	*mock.Call
}

// Migration is a helper method to define mock.On call
func (_e *MockContext_Expecter) Migration() *MockContext_Migration_Call {
	return &MockContext_Migration_Call{Call: _e.mock.On("Migration")}
}

func (_c *MockContext_Migration_Call) Run(run func()) *MockContext_Migration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Migration_Call) Return(n int64, n1 int64) *MockContext_Migration_Call {
	_c.Call.Return(n, n1)
	return _c
}

func (_c *MockContext_Migration_Call) RunAndReturn(run func() (int64, int64)) *MockContext_Migration_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function for the type MockContext
func (_mock *MockContext) Notify(action telebot.ChatAction) error {
	ret := _mock.Called(action)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(telebot.ChatAction) error); ok {
		r0 = returnFunc(action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockContext_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - action telebot.ChatAction
func (_e *MockContext_Expecter) Notify(action interface{}) *MockContext_Notify_Call {
	return &MockContext_Notify_Call{Call: _e.mock.On("Notify", action)}
}

func (_c *MockContext_Notify_Call) Run(run func(action telebot.ChatAction)) *MockContext_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telebot.ChatAction
		if args[0] != nil {
			arg0 = args[0].(telebot.ChatAction)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Notify_Call) Return(err error) *MockContext_Notify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Notify_Call) RunAndReturn(run func(action telebot.ChatAction) error) *MockContext_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// Payment provides a mock function for the type MockContext
func (_mock *MockContext) Payment() *telebot.Payment {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payment")
	}

	var r0 *telebot.Payment
	if returnFunc, ok := ret.Get(0).(func() *telebot.Payment); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Payment)
		}
	}
	return r0
}

// MockContext_Payment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payment'
type MockContext_Payment_Call struct {
	*mock.Call
}

// Payment is a helper method to define mock.On call
func (_e *MockContext_Expecter) Payment() *MockContext_Payment_Call {
	return &MockContext_Payment_Call{Call: _e.mock.On("Payment")}
}

func (_c *MockContext_Payment_Call) Run(run func()) *MockContext_Payment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Payment_Call) Return(payment *telebot.Payment) *MockContext_Payment_Call {
	_c.Call.Return(payment)
	return _c
}

func (_c *MockContext_Payment_Call) RunAndReturn(run func() *telebot.Payment) *MockContext_Payment_Call {
	_c.Call.Return(run)
	return _c
}

// Poll provides a mock function for the type MockContext
func (_mock *MockContext) Poll() *telebot.Poll {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Poll")
	}

	var r0 *telebot.Poll
	if returnFunc, ok := ret.Get(0).(func() *telebot.Poll); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Poll)
		}
	}
	return r0
}

// MockContext_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type MockContext_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
func (_e *MockContext_Expecter) Poll() *MockContext_Poll_Call {
	return &MockContext_Poll_Call{Call: _e.mock.On("Poll")}
}

func (_c *MockContext_Poll_Call) Run(run func()) *MockContext_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Poll_Call) Return(poll *telebot.Poll) *MockContext_Poll_Call {
	_c.Call.Return(poll)
	return _c
}

func (_c *MockContext_Poll_Call) RunAndReturn(run func() *telebot.Poll) *MockContext_Poll_Call {
	_c.Call.Return(run)
	return _c
}

// PollAnswer provides a mock function for the type MockContext
func (_mock *MockContext) PollAnswer() *telebot.PollAnswer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PollAnswer")
	}

	var r0 *telebot.PollAnswer
	if returnFunc, ok := ret.Get(0).(func() *telebot.PollAnswer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.PollAnswer)
		}
	}
	return r0
}

// MockContext_PollAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollAnswer'
type MockContext_PollAnswer_Call struct {
	*mock.Call
}

// PollAnswer is a helper method to define mock.On call
func (_e *MockContext_Expecter) PollAnswer() *MockContext_PollAnswer_Call {
	return &MockContext_PollAnswer_Call{Call: _e.mock.On("PollAnswer")}
}

func (_c *MockContext_PollAnswer_Call) Run(run func()) *MockContext_PollAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_PollAnswer_Call) Return(pollAnswer *telebot.PollAnswer) *MockContext_PollAnswer_Call {
	_c.Call.Return(pollAnswer)
	return _c
}

func (_c *MockContext_PollAnswer_Call) RunAndReturn(run func() *telebot.PollAnswer) *MockContext_PollAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// PreCheckoutQuery provides a mock function for the type MockContext
func (_mock *MockContext) PreCheckoutQuery() *telebot.PreCheckoutQuery {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreCheckoutQuery")
	}

	var r0 *telebot.PreCheckoutQuery
	if returnFunc, ok := ret.Get(0).(func() *telebot.PreCheckoutQuery); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.PreCheckoutQuery)
		}
	}
	return r0
}

// MockContext_PreCheckoutQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreCheckoutQuery'
type MockContext_PreCheckoutQuery_Call struct {
	*mock.Call
}

// PreCheckoutQuery is a helper method to define mock.On call
func (_e *MockContext_Expecter) PreCheckoutQuery() *MockContext_PreCheckoutQuery_Call {
	return &MockContext_PreCheckoutQuery_Call{Call: _e.mock.On("PreCheckoutQuery")}
}

func (_c *MockContext_PreCheckoutQuery_Call) Run(run func()) *MockContext_PreCheckoutQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_PreCheckoutQuery_Call) Return(preCheckoutQuery *telebot.PreCheckoutQuery) *MockContext_PreCheckoutQuery_Call {
	_c.Call.Return(preCheckoutQuery)
	return _c
}

func (_c *MockContext_PreCheckoutQuery_Call) RunAndReturn(run func() *telebot.PreCheckoutQuery) *MockContext_PreCheckoutQuery_Call {
	_c.Call.Return(run)
	return _c
}

// PurchasedPaidMedia provides a mock function for the type MockContext
func (_mock *MockContext) PurchasedPaidMedia() *telebot.PaidMediaPurchased {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PurchasedPaidMedia")
	}

	var r0 *telebot.PaidMediaPurchased
	if returnFunc, ok := ret.Get(0).(func() *telebot.PaidMediaPurchased); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.PaidMediaPurchased)
		}
	}
	return r0
}

// MockContext_PurchasedPaidMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurchasedPaidMedia'
type MockContext_PurchasedPaidMedia_Call struct {
	*mock.Call
}

// PurchasedPaidMedia is a helper method to define mock.On call
func (_e *MockContext_Expecter) PurchasedPaidMedia() *MockContext_PurchasedPaidMedia_Call {
	return &MockContext_PurchasedPaidMedia_Call{Call: _e.mock.On("PurchasedPaidMedia")}
}

func (_c *MockContext_PurchasedPaidMedia_Call) Run(run func()) *MockContext_PurchasedPaidMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_PurchasedPaidMedia_Call) Return(paidMediaPurchased *telebot.PaidMediaPurchased) *MockContext_PurchasedPaidMedia_Call {
	_c.Call.Return(paidMediaPurchased)
	return _c
}

func (_c *MockContext_PurchasedPaidMedia_Call) RunAndReturn(run func() *telebot.PaidMediaPurchased) *MockContext_PurchasedPaidMedia_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockContext
func (_mock *MockContext) Query() *telebot.Query {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *telebot.Query
	if returnFunc, ok := ret.Get(0).(func() *telebot.Query); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Query)
		}
	}
	return r0
}

// MockContext_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockContext_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
func (_e *MockContext_Expecter) Query() *MockContext_Query_Call {
	return &MockContext_Query_Call{Call: _e.mock.On("Query")}
}

func (_c *MockContext_Query_Call) Run(run func()) *MockContext_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Query_Call) Return(query *telebot.Query) *MockContext_Query_Call {
	_c.Call.Return(query)
	return _c
}

func (_c *MockContext_Query_Call) RunAndReturn(run func() *telebot.Query) *MockContext_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Recipient provides a mock function for the type MockContext
func (_mock *MockContext) Recipient() telebot.Recipient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recipient")
	}

	var r0 telebot.Recipient
	if returnFunc, ok := ret.Get(0).(func() telebot.Recipient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telebot.Recipient)
		}
	}
	return r0
}

// MockContext_Recipient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recipient'
type MockContext_Recipient_Call struct {
	*mock.Call
}

// Recipient is a helper method to define mock.On call
func (_e *MockContext_Expecter) Recipient() *MockContext_Recipient_Call {
	return &MockContext_Recipient_Call{Call: _e.mock.On("Recipient")}
}

func (_c *MockContext_Recipient_Call) Run(run func()) *MockContext_Recipient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Recipient_Call) Return(recipient telebot.Recipient) *MockContext_Recipient_Call {
	_c.Call.Return(recipient)
	return _c
}

func (_c *MockContext_Recipient_Call) RunAndReturn(run func() telebot.Recipient) *MockContext_Recipient_Call {
	_c.Call.Return(run)
	return _c
}

// Reply provides a mock function for the type MockContext
func (_mock *MockContext) Reply(what interface{}, opts ...interface{}) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(what, opts)
	} else {
		tmpRet = _mock.Called(what)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Reply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = returnFunc(what, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Reply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reply'
type MockContext_Reply_Call struct {
	*mock.Call
}

// Reply is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) Reply(what interface{}, opts ...interface{}) *MockContext_Reply_Call {
	return &MockContext_Reply_Call{Call: _e.mock.On("Reply",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_Reply_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_Reply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContext_Reply_Call) Return(err error) *MockContext_Reply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Reply_Call) RunAndReturn(run func(what interface{}, opts ...interface{}) error) *MockContext_Reply_Call {
	_c.Call.Return(run)
	return _c
}

// Respond provides a mock function for the type MockContext
func (_mock *MockContext) Respond(resp ...*telebot.CallbackResponse) error {
	var tmpRet mock.Arguments
	if len(resp) > 0 {
		tmpRet = _mock.Called(resp)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Respond")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...*telebot.CallbackResponse) error); ok {
		r0 = returnFunc(resp...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Respond_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Respond'
type MockContext_Respond_Call struct {
	*mock.Call
}

// Respond is a helper method to define mock.On call
//   - resp ...*telebot.CallbackResponse
func (_e *MockContext_Expecter) Respond(resp ...interface{}) *MockContext_Respond_Call {
	return &MockContext_Respond_Call{Call: _e.mock.On("Respond",
		append([]interface{}{}, resp...)...)}
}

func (_c *MockContext_Respond_Call) Run(run func(resp ...*telebot.CallbackResponse)) *MockContext_Respond_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*telebot.CallbackResponse
		var variadicArgs []*telebot.CallbackResponse
		if len(args) > 0 {
			variadicArgs = args[0].([]*telebot.CallbackResponse)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockContext_Respond_Call) Return(err error) *MockContext_Respond_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Respond_Call) RunAndReturn(run func(resp ...*telebot.CallbackResponse) error) *MockContext_Respond_Call {
	_c.Call.Return(run)
	return _c
}

// RespondAlert provides a mock function for the type MockContext
func (_mock *MockContext) RespondAlert(text string) error {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for RespondAlert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_RespondAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RespondAlert'
type MockContext_RespondAlert_Call struct {
	*mock.Call
}

// RespondAlert is a helper method to define mock.On call
//   - text string
func (_e *MockContext_Expecter) RespondAlert(text interface{}) *MockContext_RespondAlert_Call {
	return &MockContext_RespondAlert_Call{Call: _e.mock.On("RespondAlert", text)}
}

func (_c *MockContext_RespondAlert_Call) Run(run func(text string)) *MockContext_RespondAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_RespondAlert_Call) Return(err error) *MockContext_RespondAlert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_RespondAlert_Call) RunAndReturn(run func(text string) error) *MockContext_RespondAlert_Call {
	_c.Call.Return(run)
	return _c
}

// RespondText provides a mock function for the type MockContext
func (_mock *MockContext) RespondText(text string) error {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for RespondText")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_RespondText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RespondText'
type MockContext_RespondText_Call struct {
	*mock.Call
}

// RespondText is a helper method to define mock.On call
//   - text string
func (_e *MockContext_Expecter) RespondText(text interface{}) *MockContext_RespondText_Call {
	return &MockContext_RespondText_Call{Call: _e.mock.On("RespondText", text)}
}

func (_c *MockContext_RespondText_Call) Run(run func(text string)) *MockContext_RespondText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_RespondText_Call) Return(err error) *MockContext_RespondText_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_RespondText_Call) RunAndReturn(run func(text string) error) *MockContext_RespondText_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockContext
func (_mock *MockContext) Send(what interface{}, opts ...interface{}) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(what, opts)
	} else {
		tmpRet = _mock.Called(what)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = returnFunc(what, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockContext_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) Send(what interface{}, opts ...interface{}) *MockContext_Send_Call {
	return &MockContext_Send_Call{Call: _e.mock.On("Send",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_Send_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContext_Send_Call) Return(err error) *MockContext_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Send_Call) RunAndReturn(run func(what interface{}, opts ...interface{}) error) *MockContext_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendAlbum provides a mock function for the type MockContext
func (_mock *MockContext) SendAlbum(a telebot.Album, opts ...interface{}) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(a, opts)
	} else {
		tmpRet = _mock.Called(a)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendAlbum")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(telebot.Album, ...interface{}) error); ok {
		r0 = returnFunc(a, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_SendAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAlbum'
type MockContext_SendAlbum_Call struct {
	*mock.Call
}

// SendAlbum is a helper method to define mock.On call
//   - a telebot.Album
//   - opts ...interface{}
func (_e *MockContext_Expecter) SendAlbum(a interface{}, opts ...interface{}) *MockContext_SendAlbum_Call {
	return &MockContext_SendAlbum_Call{Call: _e.mock.On("SendAlbum",
		append([]interface{}{a}, opts...)...)}
}

func (_c *MockContext_SendAlbum_Call) Run(run func(a telebot.Album, opts ...interface{})) *MockContext_SendAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telebot.Album
		if args[0] != nil {
			arg0 = args[0].(telebot.Album)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContext_SendAlbum_Call) Return(err error) *MockContext_SendAlbum_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_SendAlbum_Call) RunAndReturn(run func(a telebot.Album, opts ...interface{}) error) *MockContext_SendAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// Sender provides a mock function for the type MockContext
func (_mock *MockContext) Sender() *telebot.User {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sender")
	}

	var r0 *telebot.User
	if returnFunc, ok := ret.Get(0).(func() *telebot.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.User)
		}
	}
	return r0
}

// MockContext_Sender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sender'
type MockContext_Sender_Call struct {
	*mock.Call
}

// Sender is a helper method to define mock.On call
func (_e *MockContext_Expecter) Sender() *MockContext_Sender_Call {
	return &MockContext_Sender_Call{Call: _e.mock.On("Sender")}
}

func (_c *MockContext_Sender_Call) Run(run func()) *MockContext_Sender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Sender_Call) Return(user *telebot.User) *MockContext_Sender_Call {
	_c.Call.Return(user)
	return _c
}

func (_c *MockContext_Sender_Call) RunAndReturn(run func() *telebot.User) *MockContext_Sender_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockContext
func (_mock *MockContext) Set(key string, val interface{}) {
	_mock.Called(key, val)
	return
}

// MockContext_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockContext_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - val interface{}
func (_e *MockContext_Expecter) Set(key interface{}, val interface{}) *MockContext_Set_Call {
	return &MockContext_Set_Call{Call: _e.mock.On("Set", key, val)}
}

func (_c *MockContext_Set_Call) Run(run func(key string, val interface{})) *MockContext_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContext_Set_Call) Return() *MockContext_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_Set_Call) RunAndReturn(run func(key string, val interface{})) *MockContext_Set_Call {
	_c.Run(run)
	return _c
}

// Ship provides a mock function for the type MockContext
func (_mock *MockContext) Ship(what ...interface{}) error {
	var tmpRet mock.Arguments
	if len(what) > 0 {
		tmpRet = _mock.Called(what)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Ship")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = returnFunc(what...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Ship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ship'
type MockContext_Ship_Call struct {
	*mock.Call
}

// Ship is a helper method to define mock.On call
//   - what ...interface{}
func (_e *MockContext_Expecter) Ship(what ...interface{}) *MockContext_Ship_Call {
	return &MockContext_Ship_Call{Call: _e.mock.On("Ship",
		append([]interface{}{}, what...)...)}
}

func (_c *MockContext_Ship_Call) Run(run func(what ...interface{})) *MockContext_Ship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockContext_Ship_Call) Return(err error) *MockContext_Ship_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Ship_Call) RunAndReturn(run func(what ...interface{}) error) *MockContext_Ship_Call {
	_c.Call.Return(run)
	return _c
}

// ShippingQuery provides a mock function for the type MockContext
func (_mock *MockContext) ShippingQuery() *telebot.ShippingQuery {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShippingQuery")
	}

	var r0 *telebot.ShippingQuery
	if returnFunc, ok := ret.Get(0).(func() *telebot.ShippingQuery); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.ShippingQuery)
		}
	}
	return r0
}

// MockContext_ShippingQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShippingQuery'
type MockContext_ShippingQuery_Call struct {
	*mock.Call
}

// ShippingQuery is a helper method to define mock.On call
func (_e *MockContext_Expecter) ShippingQuery() *MockContext_ShippingQuery_Call {
	return &MockContext_ShippingQuery_Call{Call: _e.mock.On("ShippingQuery")}
}

func (_c *MockContext_ShippingQuery_Call) Run(run func()) *MockContext_ShippingQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_ShippingQuery_Call) Return(shippingQuery *telebot.ShippingQuery) *MockContext_ShippingQuery_Call {
	_c.Call.Return(shippingQuery)
	return _c
}

func (_c *MockContext_ShippingQuery_Call) RunAndReturn(run func() *telebot.ShippingQuery) *MockContext_ShippingQuery_Call {
	_c.Call.Return(run)
	return _c
}

// Text provides a mock function for the type MockContext
func (_mock *MockContext) Text() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Text")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContext_Text_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Text'
type MockContext_Text_Call struct {
	*mock.Call
}

// Text is a helper method to define mock.On call
func (_e *MockContext_Expecter) Text() *MockContext_Text_Call {
	return &MockContext_Text_Call{Call: _e.mock.On("Text")}
}

func (_c *MockContext_Text_Call) Run(run func()) *MockContext_Text_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Text_Call) Return(s string) *MockContext_Text_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContext_Text_Call) RunAndReturn(run func() string) *MockContext_Text_Call {
	_c.Call.Return(run)
	return _c
}

// ThreadID provides a mock function for the type MockContext
func (_mock *MockContext) ThreadID() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ThreadID")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockContext_ThreadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThreadID'
type MockContext_ThreadID_Call struct {
	*mock.Call
}

// ThreadID is a helper method to define mock.On call
func (_e *MockContext_Expecter) ThreadID() *MockContext_ThreadID_Call {
	return &MockContext_ThreadID_Call{Call: _e.mock.On("ThreadID")}
}

func (_c *MockContext_ThreadID_Call) Run(run func()) *MockContext_ThreadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_ThreadID_Call) Return(n int) *MockContext_ThreadID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockContext_ThreadID_Call) RunAndReturn(run func() int) *MockContext_ThreadID_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function for the type MockContext
func (_mock *MockContext) Topic() *telebot.Topic {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 *telebot.Topic
	if returnFunc, ok := ret.Get(0).(func() *telebot.Topic); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Topic)
		}
	}
	return r0
}

// MockContext_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockContext_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockContext_Expecter) Topic() *MockContext_Topic_Call {
	return &MockContext_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockContext_Topic_Call) Run(run func()) *MockContext_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Topic_Call) Return(topic *telebot.Topic) *MockContext_Topic_Call {
	_c.Call.Return(topic)
	return _c
}

func (_c *MockContext_Topic_Call) RunAndReturn(run func() *telebot.Topic) *MockContext_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockContext
func (_mock *MockContext) Update() telebot.Update {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 telebot.Update
	if returnFunc, ok := ret.Get(0).(func() telebot.Update); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(telebot.Update)
	}
	return r0
}

// MockContext_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockContext_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
func (_e *MockContext_Expecter) Update() *MockContext_Update_Call {
	return &MockContext_Update_Call{Call: _e.mock.On("Update")}
}

func (_c *MockContext_Update_Call) Run(run func()) *MockContext_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Update_Call) Return(update telebot.Update) *MockContext_Update_Call {
	_c.Call.Return(update)
	return _c
}

func (_c *MockContext_Update_Call) RunAndReturn(run func() telebot.Update) *MockContext_Update_Call {
	_c.Call.Return(run)
	return _c
}
